#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🚀 Running pre-commit checks..."

echo "📝 Running linter..."
npm run lint

echo "🧪 Running tests..."
npm run test

echo "🔍 Running type check..."
npm run type-check

echo "✅ All checks passed!"
